export default function Disclaimer() {
  return (
    <section className="py-16 px-6 border-t border-white/5">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-8">
          <h3 className="text-lg font-medium text-white mb-4">Disclaimer & Privacy</h3>
        </div>

        <div className="backdrop-blur-lg bg-white/5 rounded-2xl p-8 border border-white/10">
          <div className="space-y-6 text-sm text-gray-400 leading-relaxed">
            <p>
              <strong className="text-gray-300">Entertainment Purpose Only:</strong> Pathways is an AI-powered entertainment application designed for creative exploration and self-reflection. All simulations, predictions, and results are generated by artificial intelligence and should not be considered as factual predictions, professional advice, or guaranteed outcomes.
            </p>
            
            <p>
              <strong className="text-gray-300">Simulation Nature:</strong> The alternate life paths, butterfly effect scores, and ghost messages are creative interpretations based on AI algorithms. They do not represent actual future events, parallel universes, or scientifically validated predictions about your life.
            </p>

            <p>
              <strong className="text-gray-300">No Liability:</strong> We are not responsible for any decisions made based on simulation results. This app is meant to inspire thought and creativity, not to guide major life decisions.
            </p>

            <div className="pt-4 border-t border-white/5 flex flex-wrap justify-center gap-6 text-xs">
              <a href="#" className="text-violet-300 hover:text-violet-200 transition-colors cursor-pointer whitespace-nowrap">
                Privacy Policy
              </a>
              <a href="#" className="text-violet-300 hover:text-violet-200 transition-colors cursor-pointer whitespace-nowrap">
                Terms of Service
              </a>
              <a href="#" className="text-violet-300 hover:text-violet-200 transition-colors cursor-pointer whitespace-nowrap">
                Contact Support
              </a>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 text-center space-y-3">
          <p className="text-xs text-gray-500">
            © 2025 Pathways. All rights reserved.
          </p>
          <a 
            href="https://readdy.ai/?ref=logo" 
            target="_blank" 
            rel="noopener noreferrer"
            className="inline-block text-xs text-gray-600 hover:text-violet-400 transition-colors cursor-pointer whitespace-nowrap"
          >
            Powered by Readdy
          </a>
        </div>
      </div>
    </section>
  );
}
